<?php

namespace App\Services;

use App\Jobs\Send2faVerificationCodeJob;
use App\Models\User;
use Illuminate\Support\Facades\Log;

class TwoFactorAuthService
{
    public function generateCode(User $user): string
    {
        $codeLength = max(4, (int) config('services.two_factor.code_length', 6));
        $code = $this->generateNumericCode($codeLength);

        $user->update([
            'two_factor_code' => $code,
            'two_factor_code_expires_at' => now()->addMinutes($this->timeoutMinutes()),
        ]);

        Log::info('2FA code generated', [
            'user_id' => $user->id,
            'phone' => $user->phone,
        ]);

        Send2faVerificationCodeJob::dispatch($user->id, $code);

        return $code;
    }

    public function verify(User $user, string $code): bool
    {
        // The $user instance passed in may have been resolved earlier in the request
        // (e.g. auth()->user()) and could be stale relative to a code generated by a
        // previous request -- always read the current DB state before comparing.
        $user->refresh();

        if (! $user->two_factor_code || ! $user->two_factor_code_expires_at || $user->two_factor_code_expires_at->isPast()) {
            Log::warning('2FA code expired or not found', [
                'user_id' => $user->id,
            ]);

            return false;
        }

        $isValid = hash_equals($user->two_factor_code, $code);

        if ($isValid) {
            $user->update([
                'two_factor_code' => null,
                'two_factor_code_expires_at' => null,
            ]);
            Log::info('2FA verified successfully', [
                'user_id' => $user->id,
            ]);
        } else {
            Log::warning('2FA verification failed', [
                'user_id' => $user->id,
            ]);
        }

        return $isValid;
    }

    public function isEnabled(User $user): bool
    {
        return $user->two_factor_enabled;
    }

    public function enable(User $user): void
    {
        $user->update([
            'two_factor_enabled' => true,
        ]);

        Log::info('2FA enabled', [
            'user_id' => $user->id,
        ]);
    }

    public function disable(User $user): void
    {
        $user->update([
            'two_factor_enabled' => false,
        ]);

        Log::info('2FA disabled', [
            'user_id' => $user->id,
        ]);
    }

    /**
     * Minutes a generated 2FA code stays valid for, read from TWO_FACTOR_TIMEOUT
     * (services.two_factor.timeout_minutes), defaulting to 2 (the previous hardcoded value).
     */
    protected function timeoutMinutes(): int
    {
        return max(1, (int) config('services.two_factor.timeout_minutes', 2));
    }

    /**
     * Generates a random numeric code with exactly $length digits (no leading zero,
     * matching the previous fixed-6-digit random_int(100000, 999999) behavior).
     */
    protected function generateNumericCode(int $length): string
    {
        $min = (int) ('1'.str_repeat('0', $length - 1));
        $max = (int) str_repeat('9', $length);

        return (string) random_int($min, $max);
    }
}
