<?php

namespace App\Services;

use App\Jobs\Send2faVerificationCodeJob;
use App\Models\User;
use Illuminate\Support\Facades\Log;

class TwoFactorAuthService
{
    protected const CODE_EXPIRY_MINUTES = 2;

    public function generateCode(User $user): string
    {
        $code = (string) random_int(100000, 999999);

        $user->update([
            'two_factor_code' => $code,
            'two_factor_code_expires_at' => now()->addMinutes(self::CODE_EXPIRY_MINUTES),
        ]);

        Log::info('2FA code generated', [
            'user_id' => $user->id,
            'phone' => $user->phone,
        ]);

        Send2faVerificationCodeJob::dispatch($user->id, $code);

        return $code;
    }

    public function verify(User $user, string $code): bool
    {
        // The $user instance passed in may have been resolved earlier in the request
        // (e.g. auth()->user()) and could be stale relative to a code generated by a
        // previous request -- always read the current DB state before comparing.
        $user->refresh();

        if (! $user->two_factor_code || ! $user->two_factor_code_expires_at || $user->two_factor_code_expires_at->isPast()) {
            Log::warning('2FA code expired or not found', [
                'user_id' => $user->id,
            ]);

            return false;
        }

        $isValid = hash_equals($user->two_factor_code, $code);

        if ($isValid) {
            $user->update([
                'two_factor_code' => null,
                'two_factor_code_expires_at' => null,
            ]);
            Log::info('2FA verified successfully', [
                'user_id' => $user->id,
            ]);
        } else {
            Log::warning('2FA verification failed', [
                'user_id' => $user->id,
            ]);
        }

        return $isValid;
    }

    public function isEnabled(User $user): bool
    {
        return $user->two_factor_enabled;
    }

    public function enable(User $user): void
    {
        $user->update([
            'two_factor_enabled' => true,
        ]);

        Log::info('2FA enabled', [
            'user_id' => $user->id,
        ]);
    }

    public function disable(User $user): void
    {
        $user->update([
            'two_factor_enabled' => false,
        ]);

        Log::info('2FA disabled', [
            'user_id' => $user->id,
        ]);
    }
}
